package idwall.desafio.builder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ricci
 */
public class TextoBuilder {

    public static final String BIBLIA_SEM_FORMATACAO = "In the beginning God created the heavens and the earth. "
            + "Now the earth was formless and empty, darkness was over the surface "
            + "of the deep, and the Spirit of God was hovering over the waters.\n"
            + "\n"
            + "And God said, \"Let there be light,\" and there was light. God saw that "
            + "the light was good, and he separated the light from the darkness. "
            + "God called the light \"day,\" and the darkness he called \"night.\" "
            + "And there was evening, and there was morning - the first day.";

    public static final String VIDA_SEM_FORMATACAO = "Um dia descobrimos que beijar uma pessoa para esquecer outra, é bobagem.\n"
            + "Você não só não esquece a outra pessoa como pensa muito mais nela...\n"
            + "Um dia nós percebemos que as mulheres têm instinto \"caçador\" e fazem qualquer homem sofrer ...\n"
            + "Um dia descobrimos que se apaixonar é inevitável...\n"
            + "Um dia percebemos que as melhores provas de amor são as mais simples...\n"
            + "Um dia percebemos que o comum não nos atrai...\n"
            + "Um dia saberemos que ser classificado como \"bonzinho\" não é bom...\n"
            + "Um dia perceberemos que a pessoa que nunca te liga é a que mais pensa em você...\n"
            + "Um dia percebemos que somos muito importante para alguém, mas não damos valor a isso...\n"
            + "Um dia percebemos como aquele amigo faz falta, mas ai já é tarde demais...\n"
            + "Enfim...\n"
            + "Um dia descobrimos que apesar de viver quase um século esse tempo todo não é suficiente para realizarmos todos os nossos sonhos, para beijarmos todas as bocas que nos atraem, para dizer o que tem de ser dito...\n"
            + "O jeito é: ou nos conformamos com a falta de algumas coisas na nossa vida ou lutamos para realizar todas as nossas loucuras...";

    public static final String BIBLIA_40_CARACTERES = "In the beginning God created the heavens\n"
            + "and the earth. Now the earth was\n"
            + "formless and empty, darkness was over\n"
            + "the surface of the deep, and the Spirit\n"
            + "of God was hovering over the waters.\n"
            + "\n"
            + "And God said, \"Let there be light,\" and\n"
            + "there was light. God saw that the light\n"
            + "was good, and he separated the light\n"
            + "from the darkness. God called the light\n"
            + "\"day,\" and the darkness he called\n"
            + "\"night.\" And there was evening, and\n"
            + "there was morning - the first day.";

    public static final String BIBLIA_40_CARACTERES_JUSTIFICADO = "In the beginning God created the heavens\n"
            + "and   the   earth.  Now  the  earth  was\n"
            + "formless  and  empty,  darkness was over\n"
            + "the  surface of the deep, and the Spirit\n"
            + "of  God  was  hovering  over the waters.\n"
            + "\n"
            + "And  God said, \"Let there be light,\" and\n"
            + "there  was light. God saw that the light\n"
            + "was  good,  and  he  separated the light\n"
            + "from  the darkness. God called the light\n"
            + "\"day,\"   and   the  darkness  he  called\n"
            + "\"night.\"  And  there  was  evening,  and\n"
            + "there  was  morning  -  the  first  day.";

    public static final String BIBLIA_20_CARACTERES_JUSTIFICADO = "In the beginning God\n"
            + "created  the heavens\n"
            + "and  the  earth. Now\n"
            + "the     earth    was\n"
            + "formless  and empty,\n"
            + "darkness   was  over\n"
            + "the  surface  of the\n"
            + "deep,     and    the\n"
            + "Spirit  of  God  was\n"
            + "hovering   over  the\n"
            + "waters.\n"
            + "\n"
            + "And  God  said, \"Let\n"
            + "there   be   light,\"\n"
            + "and     there    was\n"
            + "light.  God saw that\n"
            + "the  light was good,\n"
            + "and   he   separated\n"
            + "the  light  from the\n"
            + "darkness.        God\n"
            + "called   the   light\n"
            + "\"day,\"    and    the\n"
            + "darkness  he  called\n"
            + "\"night.\"  And  there\n"
            + "was   evening,   and\n"
            + "there  was morning -\n"
            + "the    first    day.";

    public static final String BIBLIA_20_CARACTERES = "In the beginning God\n"
            + "created the heavens\n"
            + "and the earth. Now\n"
            + "the earth was\n"
            + "formless and empty,\n"
            + "darkness was over\n"
            + "the surface of the\n"
            + "deep, and the\n"
            + "Spirit of God was\n"
            + "hovering over the\n"
            + "waters.\n"
            + "\n"
            + "And God said, \"Let\n"
            + "there be light,\"\n"
            + "and there was\n"
            + "light. God saw that\n"
            + "the light was good,\n"
            + "and he separated\n"
            + "the light from the\n"
            + "darkness. God\n"
            + "called the light\n"
            + "\"day,\" and the\n"
            + "darkness he called\n"
            + "\"night.\" And there\n"
            + "was evening, and\n"
            + "there was morning -\n"
            + "the first day.";

    public static final String BIBLIA_10_CARACTERES = "In the\n"
            + "beginning\n"
            + "God\n"
            + "created\n"
            + "the\n"
            + "heavens\n"
            + "and the\n"
            + "earth.\n"
            + "Now the\n"
            + "earth was\n"
            + "formless\n"
            + "and\n"
            + "empty,\n"
            + "darkness\n"
            + "was over\n"
            + "the\n"
            + "surface\n"
            + "of the\n"
            + "deep, and\n"
            + "the\n"
            + "Spirit of\n"
            + "God was\n"
            + "hovering\n"
            + "over\n"
            + "the\n"
            + "waters.\n"
            + "\n"
            + "And God\n"
            + "said,\n"
            + "\"Let\n"
            + "there be\n"
            + "light,\"\n"
            + "and there\n"
            + "was\n"
            + "light.\n"
            + "God saw\n"
            + "that the\n"
            + "light was\n"
            + "good, and\n"
            + "he\n"
            + "separated\n"
            + "the light\n"
            + "from the\n"
            + "darkness.\n"
            + "God\n"
            + "called\n"
            + "the light\n"
            + "\"day,\"\n"
            + "and the\n"
            + "darkness\n"
            + "he called\n"
            + "\"night.\"\n"
            + "And there\n"
            + "was\n"
            + "evening,\n"
            + "and there\n"
            + "was\n"
            + "morning -\n"
            + "the first\n"
            + "day.";

    public static final String VIDA_40_CARACTERES = "Um dia descobrimos que beijar uma pessoa\n"
            + "para esquecer outra, é bobagem.\n"
            + "Você não só não esquece a outra pessoa\n"
            + "como pensa muito mais nela...\n"
            + "Um dia nós percebemos que as mulheres\n"
            + "têm instinto \"caçador\" e fazem qualquer\n"
            + "homem sofrer ...\n"
            + "Um dia descobrimos que se apaixonar é\n"
            + "inevitável...\n"
            + "Um dia percebemos que as melhores provas\n"
            + "de amor são as mais simples...\n"
            + "Um dia percebemos que o comum não nos\n"
            + "atrai...\n"
            + "Um dia saberemos que ser classificado\n"
            + "como \"bonzinho\" não é bom...\n"
            + "Um dia perceberemos que a pessoa que\n"
            + "nunca te liga é a que mais pensa em\n"
            + "você...\n"
            + "Um dia percebemos que somos muito\n"
            + "importante para alguém, mas não damos\n"
            + "valor a isso...\n"
            + "Um dia percebemos como aquele amigo faz\n"
            + "falta, mas ai já é tarde demais...\n"
            + "Enfim...\n"
            + "Um dia descobrimos que apesar de viver\n"
            + "quase um século esse tempo todo não é\n"
            + "suficiente para realizarmos todos os\n"
            + "nossos sonhos, para beijarmos todas as\n"
            + "bocas que nos atraem, para dizer o que\n"
            + "tem de ser dito...\n"
            + "O jeito é: ou nos conformamos com a\n"
            + "falta de algumas coisas na nossa vida\n"
            + "ou lutamos para realizar todas as\n"
            + "nossas loucuras...";

    public static final String VIDA_20_CARACTERTES = "Um dia descobrimos\n"
            + "que beijar uma\n"
            + "pessoa para\n"
            + "esquecer outra, é\n"
            + "bobagem.\n"
            + "Você não só não\n"
            + "esquece a outra\n"
            + "pessoa como pensa\n"
            + "muito mais\n"
            + "nela...\n"
            + "Um dia nós\n"
            + "percebemos que as\n"
            + "mulheres têm\n"
            + "instinto \"caçador\"\n"
            + "e fazem qualquer\n"
            + "homem sofrer ...\n"
            + "Um dia descobrimos\n"
            + "que se apaixonar é\n"
            + "inevitável...\n"
            + "Um dia percebemos\n"
            + "que as melhores\n"
            + "provas de amor são\n"
            + "as mais\n"
            + "simples...\n"
            + "Um dia percebemos\n"
            + "que o comum não nos\n"
            + "atrai...\n"
            + "Um dia saberemos que\n"
            + "ser classificado\n"
            + "como \"bonzinho\" não\n"
            + "é bom...\n"
            + "Um dia perceberemos\n"
            + "que a pessoa que\n"
            + "nunca te liga é a\n"
            + "que mais pensa em\n"
            + "você...\n"
            + "Um dia percebemos\n"
            + "que somos muito\n"
            + "importante para\n"
            + "alguém, mas não\n"
            + "damos valor a\n"
            + "isso...\n"
            + "Um dia percebemos\n"
            + "como aquele amigo\n"
            + "faz falta, mas ai\n"
            + "já é tarde\n"
            + "demais...\n"
            + "Enfim...\n"
            + "Um dia descobrimos\n"
            + "que apesar de viver\n"
            + "quase um século\n"
            + "esse tempo todo não\n"
            + "é suficiente para\n"
            + "realizarmos todos\n"
            + "os nossos sonhos,\n"
            + "para beijarmos\n"
            + "todas as bocas que\n"
            + "nos atraem, para\n"
            + "dizer o que tem de\n"
            + "ser dito...\n"
            + "O jeito é: ou nos\n"
            + "conformamos com a\n"
            + "falta de algumas\n"
            + "coisas na nossa\n"
            + "vida ou lutamos\n"
            + "para realizar todas\n"
            + "as nossas\n"
            + "loucuras...";

}
